#!/bin/bash
sum=0

for item in $*
do	
				echo $item | grep [^0-9+-] > /dev/null
				if [ $? -eq 0 ]
				then
								echo "Sorry, '$item' is not a number"
								exit
				fi
	sum=$((sum+item))
done
echo "$sum"
